name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  amp-camp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build neuron site 🔧
    run |
      npm install
      gulp
    - name: Deploy to gh-pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .amp-camp/output/
